[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = true
evm_version = "prague"
solc_version = "0.8.28"

[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"
bsc_testnet = "https://bsc-testnet.public.blastapi.io"
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
